/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-09-01 at 21:09:02 UTC 
 * Modify at your own risk.
 */

package com.appspot.xtrem_engine_2015.xservice;

/**
 * Service definition for Xservice (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link XserviceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Xservice extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the xservice library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://xtrem-engine-2015.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "xservice/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Xservice(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Xservice(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "hello".
   *
   * This request holds the parameters needed by the xservice server.  After setting any optional
   * parameters, call the {@link Hello#execute()} method to invoke the remote operation.
   *
   * @param name
   * @return the request
   */
  public Hello hello(java.lang.String name) throws java.io.IOException {
    Hello result = new Hello(name);
    initialize(result);
    return result;
  }

  public class Hello extends XserviceRequest<com.appspot.xtrem_engine_2015.xservice.model.XEIDTO> {

    private static final String REST_PATH = "hello/{name}";

    /**
     * Create a request for the method "hello".
     *
     * This request holds the parameters needed by the the xservice server.  After setting any
     * optional parameters, call the {@link Hello#execute()} method to invoke the remote operation.
     * <p> {@link
     * Hello#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param name
     * @since 1.13
     */
    protected Hello(java.lang.String name) {
      super(Xservice.this, "POST", REST_PATH, null, com.appspot.xtrem_engine_2015.xservice.model.XEIDTO.class);
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
    }

    @Override
    public Hello setAlt(java.lang.String alt) {
      return (Hello) super.setAlt(alt);
    }

    @Override
    public Hello setFields(java.lang.String fields) {
      return (Hello) super.setFields(fields);
    }

    @Override
    public Hello setKey(java.lang.String key) {
      return (Hello) super.setKey(key);
    }

    @Override
    public Hello setOauthToken(java.lang.String oauthToken) {
      return (Hello) super.setOauthToken(oauthToken);
    }

    @Override
    public Hello setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Hello) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Hello setQuotaUser(java.lang.String quotaUser) {
      return (Hello) super.setQuotaUser(quotaUser);
    }

    @Override
    public Hello setUserIp(java.lang.String userIp) {
      return (Hello) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public Hello setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @Override
    public Hello set(String parameterName, Object value) {
      return (Hello) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "request".
   *
   * This request holds the parameters needed by the xservice server.  After setting any optional
   * parameters, call the {@link Request#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.xtrem_engine_2015.xservice.model.XEIDTO}
   * @return the request
   */
  public Request request(com.appspot.xtrem_engine_2015.xservice.model.XEIDTO content) throws java.io.IOException {
    Request result = new Request(content);
    initialize(result);
    return result;
  }

  public class Request extends XserviceRequest<com.appspot.xtrem_engine_2015.xservice.model.XEIDTO> {

    private static final String REST_PATH = "request";

    /**
     * Create a request for the method "request".
     *
     * This request holds the parameters needed by the the xservice server.  After setting any
     * optional parameters, call the {@link Request#execute()} method to invoke the remote operation.
     * <p> {@link
     * Request#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.xtrem_engine_2015.xservice.model.XEIDTO}
     * @since 1.13
     */
    protected Request(com.appspot.xtrem_engine_2015.xservice.model.XEIDTO content) {
      super(Xservice.this, "POST", REST_PATH, content, com.appspot.xtrem_engine_2015.xservice.model.XEIDTO.class);
    }

    @Override
    public Request setAlt(java.lang.String alt) {
      return (Request) super.setAlt(alt);
    }

    @Override
    public Request setFields(java.lang.String fields) {
      return (Request) super.setFields(fields);
    }

    @Override
    public Request setKey(java.lang.String key) {
      return (Request) super.setKey(key);
    }

    @Override
    public Request setOauthToken(java.lang.String oauthToken) {
      return (Request) super.setOauthToken(oauthToken);
    }

    @Override
    public Request setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Request) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Request setQuotaUser(java.lang.String quotaUser) {
      return (Request) super.setQuotaUser(quotaUser);
    }

    @Override
    public Request setUserIp(java.lang.String userIp) {
      return (Request) super.setUserIp(userIp);
    }

    @Override
    public Request set(String parameterName, Object value) {
      return (Request) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Xservice}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Xservice}. */
    @Override
    public Xservice build() {
      return new Xservice(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link XserviceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setXserviceRequestInitializer(
        XserviceRequestInitializer xserviceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(xserviceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
